version: '3'

services:
  api:
    build:
      context: .docker/node
      dockerfile: Dockerfile
    command: ["-c", "/home/node/app/entrypoint.sh"]
    entrypoint: ["/bin/sh"]
    container_name: api_kvendas
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    container_name: dbkvendas
    restart: always
    # tity: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis_kvendas
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_kvendas
    # tity: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
